### ISSUE TITLE
Misc Consistency Issues and subsetting

### ISSUE THREAD

**Issue by hfhchan** [tamcy/CYanHeiHK#10]
In https://github.com/google/fonts/issues/396#issue-181311259 I posted results of my analysis of a one year excerpt of 東方日報 to indicate which common characters are missing.

The following are a few minor consistency issues:
![image](https://cloud.githubusercontent.com/assets/8191296/21458779/415df798-c974-11e6-85d4-3ee9ef7a3a30.png)

Also I haven't checked if all these characters are present in the subsetted version.

The block of characters is as follows:
奬戥擸捭啩説舁仵揈脗
𠝹瀡趷掹孻釿麖睩𠻹𨋢
骹摷忟鈪舸鯭搲咇飊㩒
裇湋鈈𢭃彅脱郜蹚𥄫泆
税噃溋鏸閲
兑藴醖鋭丢𦉘椗𦧲𤓓鰵
啅襇拃啹𦟌抦揦飇嗮膦
酞肼氘腼飱犂掮鱇璈瑆
駹䮎琋睎㷧廼錤原

**Comment by hfhchan** [comment]
The bottom fire of 蘸 should be under 隹 instead of spread evenly under the bottom (i.e. use G-source glyph).

**Comment by tamcy** [comment]
Thank you. Base on you findings I've added 睩,舁,趷,飱,鰵 to the subset. 蘸 will be fixed too.

**Comment by tamcy** [comment]
膦 and 腼 are also updated in v1.008.

Thank you for pointing out the inconsistency issue. However I'll leave it unchanged as it isn't fatal (also 郜 is not very frequently used). And I have to confess that due to my laziness and lack of time devoted to this project, there are inconsistencies here and there that I am aware of but decided to leave them as-is. One example is whether the font needs to take 避重捺 strictly and seriously (heck, there is even a character exhibiting different 避重捺 behavior in different weight which I overlooked). I hope to review/correct these when SHS 2.0 is out. But again, I don't think it is very disturbing in daily use. Thank you for your understanding.

**Comment by hfhchan** [comment]
Sure thanks! Hope I am not too demanding here.  I am interested in making some experimental changes myself, but I have no idea how :(

**Comment by tamcy** [comment]
Have you checked my comment posted in #3?

**Comment by hfhchan** [comment]
yes, i just posted a few min before your reply.  will check it out soon :)
